#!/bin/sh

autoreconf -fiI config

#libtoolize --automake --force --copy \
#&& aclocal -I config \
#&& autoheader \
#&& automake --gnu --add-missing --copy \
#&& autoconf

if test `basename ${0}` = "bootstrap-and-dist" ; then
	./configure --with-libtools=$HOME/aplic/libtools && make dist-bzip2
fi
