#!/bin/bash

BOOST=/apps/BOOST/1.52.0 

module load boost
module load python
script=$(readlink -f "$0")
scriptpath=$(dirname "$script")
srcpath=$scriptpath/../..
versionpath=$srcpath/../..
cd $versionpath
version=${PWD##*/}
dest=$versionpath/default
mkdir -p $dest
cd $srcpath
log=$srcpath/log
./bootstrap > $log 2>&1
./configure --prefix=$dest --with-boost=$BOOST >> $log 2>&1
make >> $log 2>&1 
make install >> $log 2>&1
path=$versionpath/..
if [ -d $path/default ]
then
  rm $path/default
fi
ln -s $path/$version $path/default
