#!/bin/bash

source settings

script=$(readlink -f "$0")
scriptpath=$(dirname "$script")
apppath=$scriptpath/../..
version=`$scriptpath/version`
target=$APPDIR/$APP/$version/src
module=$MODULEDIR/$MODULE
cmd=`ssh $SSHTARGET "rm -fr $target && mkdir -p $target"`
$command
cd $apppath
repo=${PWD##*/}
cd $scriptpath
scp -r $apppath/../$repo $SSHTARGET:$target/
cmd=`ssh $SSHTARGET "cd $target/$repo/.packaging/marenostrum/ && ./deploy"`
scp module $SSHTARGET:$module/$version
cmd=`ssh $SSHTARGET "rm -f $module/defaut && ln -s $module/$version $module/defaut"`
