#!/bin/bash

if test "${FOLDING_HOME}" == ""; then
	mypath=`readlink -f ${0}`
	mydir=`dirname ${mypath}`
	mydir=`dirname ${mydir}`
	export FOLDING_HOME=${mydir}
fi

if test $# -ge 2 ; then
	echo Sorry... you can provide one tracefile at a time
else
	$FOLDING_HOME/bin/wxfolding.py $@
fi

