#!/bin/bash

if test "${FOLDING_HOME}" == ""; then
	mypath=`readlink -f ${0}`
	mydir=`dirname ${mypath}`
	mydir=`dirname ${mydir}`
	export FOLDING_HOME=${mydir}
fi

if test $# -ge 2 ; then
	echo Sorry... you can provide one tracefile at a time
else
	if test $# -eq 1 ; then
		filename=$1
		if test ! -r ${filename} ; then
			echo Sorry... ${filename} cannot be read. Check that it exists!
			exit
		fi
		extension="${filename##*.}"
		if test "${extension}" != "prv" ; then
			echo Sorry... ${filename} does not seem to be a Paraver tracefile!
			exit
		fi
		$FOLDING_HOME/bin/wxfolding.py ${filename}
	else
		$FOLDING_HOME/bin/wxfolding.py
	fi
fi

