#!/bin/bash

if test "${FOLDING_HOME}" == ""; then
	mypath=`readlink -f ${0}`
	mydir=`dirname ${mypath}`
	mydir=`dirname ${mydir}`
	export FOLDING_HOME=${mydir}
fi

if test $# -ne 2 ; then
	echo Sorry... you must provide an .wxfolding file to continue
else
	$FOLDING_HOME/bin/wxfolding_viewer.py $@
fi

